### ISSUE TITLE
Is there a wrap around terminal feature?

### ISSUE THREAD

**Issue by TwistingTwists** [maaslalani/slides#101]
Problem:
Since my markdown file has LONG lines, a word wrap would enable me see lines. I see lines going out of screen now.

Solution : Possible Word wrap around 80 characters or width of terminal 

May be this feature is already present and I could not figure it out, if so, Let me know! :)

**Comment by maaslalani** [comment]
Hey! We're possibly going to add word wrapping here: https://github.com/maaslalani/slides/pull/84

**Comment by TwistingTwists** [comment]
Nice!

**Comment by marcotrosi** [comment]
@maaslalani  sorry for the question (cause I didn't check myself), but does slides have support for centered and block text, in addition to the left aligned text? Any plans? Even possible?

**Comment by maaslalani** [comment]
Yea I want to add center and right aligning in the future.

https://github.com/maaslalani/slides/issues/56#issuecomment-869192906

**Comment by maaslalani** [comment]
@TwistingTwists Word wrapping should be enabled now 😄

**Comment by TwistingTwists** [comment]
awesome! Will check.

Thanks!

**Comment by expelledboy** [comment]
How do I use this?

**Comment by MadcapJake** [comment]
I think what was implemented in #84 was that it will honor the terminal width instead of just overflowing. Custom wrap prior to the terminal width is not supported afaict (or it's not documented).
