### ISSUE TITLE
PageUp / PageDown shortcut support

### ISSUE THREAD

**Issue by trgwii** [maaslalani/slides#110]
**Is your feature request related to a problem? Please describe.**
KDE Connect has a "slideshow tool", when you press left or right on this tool in the mobile app, in KDE it will emit PageUp for left / previous slide, and PageDown for right / next slide. As far as I can tell these are unconfigurable in KDE Connect (at least from GUI).

**Describe the solution you'd like**
I would like if this presentation tool supported PageUp and PageDown for changing slides.

**Comment by Janszczyrek** [comment]
#115

**Comment by maaslalani** [comment]
@trgwii This functionality should be available on latest `main` branch now 😄
