### ISSUE TITLE
code block execution doesn't always show the result 

### ISSUE THREAD

**Issue by kurtsys-howest** [maaslalani/slides#111]
**Describe the bug**
When doing code block execution, the output is shown for some cases, such as a `console.log` in javascript or a plain `ls` or `echo` in bash. However, no output is shown in other cases, such as the go example in the example slides, a `fetch` using javascript or a `curl` in bash. 

**To Reproduce**
1. Make a presentation with one slide with content
    ````
    ```bash
    curl -i google.com
    ```
    ````
2. Start the presentation
3. press `<ctrl>-e` on that slide

**Expected behavior**
show the output of the curl command

**Screenshots**
there's no output when pressing `<ctrl>-e`
![image](https://user-images.githubusercontent.com/90307389/138045513-78d139dd-d12e-4e5d-ad37-6fda9062590c.png)

**Desktop (please complete the following information):**
```
➜  openAPI uname -a
Linux flipflap 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
➜  openAPI lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

**Comment by maaslalani** [comment]
Hey! @kurtsys-howest I made some changes to fix a bug I found regarding code execution where the code won't execute more than once (https://github.com/maaslalani/slides/commit/acc4e0888113c9208561a9a666142c313a67ba23). Can you see if this bug fix also fixes your problem?

**Comment by maaslalani** [comment]
Going to close this but please reopen if this is still relevant
