### ISSUE TITLE
Arch Linux Metadata printing on first slide.

### ISSUE THREAD

**Issue by kndwin** [maaslalani/slides#124]
**Describe the bug**
Using Arch Linux, when I set metadata fields, it's not setting them but rather printing them on the first slide

**To Reproduce**
1. Install `slides` with `yay -S slides`
2. Populate `slide.md` with the following
```markdown
---
paging: %d / %d
---

# Overview

Amet placeat ipsam laborum ducimus?
```
3. Run `slides slide.md`

**Expected behavior**
The paging field should update based on what I inputed

**Screenshots**
![image](https://user-images.githubusercontent.com/22161029/148683351-b0c18b89-d0b7-44bd-a3b1-96b2d53b1ad4.png)

**Desktop (please complete the following information):**
```
[ notion-nextjs-cms  ] neofetch
                   -`                    knd@donne 
                  .o+`                   --------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: XPS 17 9700 
               `+oooooo:                 Kernel: 5.15.7-arch1-1 
               -+oooooo+:                Uptime: 9 hours, 15 mins 
             `/:-:++oooo+:               Packages: 1448 (pacman) 
            `/++++/+++++++:              Shell: bash 5.1.12 
           `/++++++++++++++:             Resolution: 1440x2560, 3440x1440, 1920x1080 
          `/+++ooooooooooooo/`           WM: i3 
         ./ooosssso++osssssso+`          Theme: Adwaita [GTK2/3] 
        .oossssso-````/ossssss+`         Icons: Adwaita [GTK2/3] 
       -osssssso.      :ssssssso.        Terminal: termite 
      :osssssss/        osssso+++.       Terminal Font: Sauce Code Pro Nerd Font 14 
     /ossssssss/        +ssssooo/-       CPU: Intel i7-10750H (12) @ 5.000GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: NVIDIA GeForce GTX 1650 Ti Mobile 
  `+sso+:-`                 `.-/+oso:    GPU: Intel CometLake-H GT2 [UHD Graphics] 
 `++:.                           `-/+/   Memory: 3893MiB / 15746MiB 
```
**Additional context**
- Looking at other simliar [issue](https://github.com/maaslalani/slides/issues/98), I wonder if the yay package is just stale and needs the latest features to be pushed.

**Comment by kndwin** [comment]
It seems like if I add quotation marks around the metadata fields then it starts to work. The documentation didn't mention this so maybe it'll be worthwhile to either make the behavior consistent or add quotations to the documentaiton. Happy with either :)

**Example below**
```markdown
---
paging: "%d / %d"
date: ""
---
```

**Comment by maaslalani** [comment]
Thanks so much for filing this well written issue! I really appreciate it.

I will take a look and fix the documentation if not possible to make the behaviour consistent.

**Comment by maaslalani** [comment]
So it looks like the `%` (non-delimited by quotes) will cause the YAML to be invalid, which means that slides metadata parser can't parse it. I will update the documentation to ensure quotes are enabled. Thanks for this issue!

**Comment by maaslalani** [comment]
Weird, it's only when the paging information _starts_ with a `%`.

```
paging: Page %d of %d
```

works fine
