### ISSUE TITLE
Better handling of link targets

### ISSUE THREAD

**Issue by larsks** [maaslalani/slides#128]
**Is your feature request related to a problem? Please describe.**

Given an input document like:

```
## Example

This talks about issue [#122](https://github.com/maaslalani/slides/issues/122), which I'm using for an example
because I was just looking at it.
```

`slides` renders this as:

```
   ▓▓▓ Example                                                                  
                                                                                
   This talks about issue #122 https://github.com/maaslalani/slides/issues/122, 
   which I'm using for an example because I was just looking at it.             
```

**Describe the solution you'd like**

This can make the slide hard to read, especially with longer urls (direct links to github commits, links from various product catalogs, etc). I'd like a way to either (a) hide the link targets in the rendered output:

```
   ▓▓▓ Example                                                                  
                                                                                
   This talks about issue #122, which I'm using for an example because I was just looking at it.             
```

Or (b) render the links as "footnotes" on the slide instead:

```
   ▓▓▓ Example                                                                  
                                                                                
   This talks about issue #122, which I'm using for an example because I was just looking at it.             

   [#122]: https://github.com/maaslalani/slides/issues/122
```

**Comment by maaslalani** [comment]
In your `theme.json` you can change the `"link"` to be:

```json
  "link": {
    "color": "30",
    "underline": false,
    "format": " "
  },
```

The `"format"` section (which is normally `{{.text}}`) would hide it. More information on custom themes: https://github.com/maaslalani/slides#configuration

For (b) you could achieve this by editing the slides themselves, but I guess you are not controlling the slides here? Generally, you can do any text manipulation before passing the markdown into `slides` so you could do something like `curl https://example.org/slides.md | sed 's/[.*]//g' | slides` (something like this) to remove links. But, I think in this case the best option is to change the theme to remove the links from having any format.

**Comment by larsks** [comment]
Hi, thanks for the example. That definitely helps with (a) (hiding the links), although it's a shame that `format` can't be set to the empty string. Given the above example, the space between the link name and the following `,` is very obvious:

```
   ▓▓▓ Example                                                                  
                                                                                
   This talks about issue #122 , which I'm using for an example because I was just looking at it.             
```

I'm not sure I presented option (b) in a sufficiently descriptive fashion; it's not something that could really be implemented by simple postprocessing with `sed`; it requires an actual markdown parser to extract the link names and targets and then generate the appropriate footnotes at the bottom of each slide (ideally in a theme-able fashion). It probably requires support in the code.

**Comment by maaslalani** [comment]
> That definitely helps with (a) (hiding the links), although it's a shame that format can't be set to the empty string. Given the above example, the space between the link name and the following , is very obvious:

Agreed, looks like there is also a `"conceal"` option which looks like the correct solution for (a). But, it might not be working correctly https://github.com/charmbracelet/glamour/issues/121 (`slides` uses `glamour` for it's markdown rendering)

**Comment by maaslalani** [comment]
Regarding (b) `slides` doesn't implement it's own markdown processing (We rely on https://github.com/charmbracelet/glamour which relies on https://github.com/yuin/goldmark) so I don't think `slides` would be able to handle that processing.

Quick question: are you unable to modify your slides markdown file, before presenting them?

It would be quite trivial to modify the slides to include footnotes as such:

![image](https://user-images.githubusercontent.com/42545625/150244597-e8a63bf4-e003-4d08-aef1-0521b9bc8f2f.png)


```
## Example

This talks about issue [#122](#), which I'm using for an example
because I was just looking at it.

[#122](https://github.com/maaslalani/slides/issues/122)
```

**Comment by larsks** [comment]
> are you unable to modify your slides markdown file

I can, but I was hoping to have the same sources render "normally" when viewed e.g. in a browser. I'll fiddle around with this idea and what you suggested in [the previous comment](https://github.com/maaslalani/slides/issues/128#issuecomment-1017016477). Thanks for the suggestions!
