### ISSUE TITLE
Allow hiding lines of code in code block

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/slides#135]
**Is your feature request related to a problem? Please describe.**

Code for some compiled languages is quite verbose and takes up too much space on a slide and adds noise if the presenter wants to highlight one piece of code / a few lines of code. However, these lines are still needed for the code to compile and execute.

**Describe the solution you'd like**

Allow a character at the beginning or end of a line to hide the line of code but strip these characters before executing the code so it still works

**Describe alternatives you've considered**

Auto-import and fill context before compiling the code (this would be fairly brittle and language specific and give less flexibility)

**Additional context**

See discussions section.

**Comment by hayesall** [comment]
https://github.com/maaslalani/slides/discussions/134

**Comment by reitzig** [comment]
FWIW: They use `//sampleStart` and `//sampleEnd` around the displayed part on kotlinlang.org/docs
