### ISSUE TITLE
Pre-Process Doesn't Handle Newlines

### ISSUE THREAD

**Issue by Thomas-Malcolm** [maaslalani/slides#136]
**Description**
The current method for parsing pre-processed data doesn't handle newlines in process stdout, resulting in everything being on the same line.

**Reproducing**
Taking the example in the pre-processing example slide:

```
~~~graph-easy --as=boxart
[ A ] - to -> [ B ]
~~~
```

Produces:

```
┌───┐  to   ┌───┐ │ A │ ────> │ B │ └───┘       └───┘
```

**Explanation**
The output of the command being run is just added to the Block representing the whole slide ([internal/process/process.go:68](https://github.com/maaslalani/slides/blob/541979777d7594972d7bf69976c4db8a351f7468/internal/process/process.go#L68)), which then _all_ gets parsed by the markdown renderer (the newlines remain intact until [internal/model/model.go:183](https://github.com/maaslalani/slides/blob/541979777d7594972d7bf69976c4db8a351f7468/internal/model/model.go#L183)). As a markdown newline is two newlines, and processes just output single newlines, the renderer interprets the process output with no newlines.

**Temporary Solution**
I didn't open a PR because my solution is quite hacky and probably breaks some cases, but you can wrap the process output in a markdown code block so the renderer interprets it as plain text. There's almost certainly a more elegant way to do it :'D

See here: https://github.com/Thomas-Malcolm/slides/commit/15990c5772ede761bc397120ae1dd03d819533a7

**Comment by maaslalani** [comment]
If new lines are important to preserve (without wrapping) I surround the preprocessing with markdown quotes in the slides directly so that this can be decided on a case by case basis.

````markdown

```
~~~grapheasy --boxart
[ A ] -> [ B ]
~~~
```

````

Does this work for you?

**Comment by Thomas-Malcolm** [comment]
Ah yeh I see how that should work now, interestingly it doesn't though, I still get the single-line output - time for system info!

```
$ uname -a
Linux <hostname> 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
$ echo $SHELL
/bin/bash
$ go version
go version go1.17.6 linux/amd64
```

**Comment by maaslalani** [comment]
Interesting, can you try running these slides https://github.com/maaslalani/slides/blob/main/examples/preprocess.md

(Double check that the file is executable `chmod +x preprocess.md`)

There may be a bug if that still doesn't work. I can fix it if thats the case.

**Comment by Thomas-Malcolm** [comment]
Can confirm I get the same error on those slides

**Comment by maaslalani** [comment]
Thanks so much for confirming, I'll take a look at what's going on.

Also thanks so much for using slides and reporting this issue ❤️

**Comment by maaslalani** [comment]
Strange that it works for me 🤔 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/42545625/152666228-959dadfa-8aab-47ad-8329-c8119a207408.png">

**Comment by Thomas-Malcolm** [comment]
Strange, I just got back to my laptop, tried it on the same one and it... works now? Same slides binary in `~/go/bin` and same slide example as before. There shouldn't be anything that causes non-deterministic behaviour right?

I'll be using it over the next day or two a fair bit, suppose if it happens again I'll drop another comment in here

**Comment by maaslalani** [comment]
The only thing I can think of is if the result of the pre-process was cached / using an old file of the result. But, I don't think that should be the case.

Glad it works now, do let me know if this happens again! Thanks so much for double checking as well 🙂

**Comment by ylbeethoven** [comment]
I can't get this to work either

![image](https://user-images.githubusercontent.com/1949110/158322794-448a6cc7-bc79-4c5f-beba-c3a9257df8ad.png)

I installed slides using snap, my terminal is Kitty using ZSH with powerlevel10k theme.

**Comment by maaslalani** [comment]
@Thomas-Malcolm Hey! Guessing this wasn't reproducible and just a weird blip, do re-open this issue if you encounter this again 😄
