### ISSUE TITLE
Consider shipping release tarball with vendored dependencies

### ISSUE THREAD

**Issue by illiliti** [maaslalani/slides#137]
**Is your feature request related to a problem? Please describe.**

Current approach requires internet connection in order to build slides. With vendored dependencies, i can build slides from source **without internet connection** by using this command: go build -mod=vendor

**Describe the solution you'd like**

For example, [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy/tree/master/vendor) does this by simply maintaining vendor directory. You can also setup CI to vendor dependencies into release tarball without needing to keep vendor directory within repository. Here is the command that can be used for this: `go mod vendor`

**Comment by maaslalani** [comment]
Hi, there! I've set up a `vendor` branch if you still need this :)

https://github.com/maaslalani/slides/tree/vendor

**Comment by illiliti** [comment]
Thank you very much!
