### ISSUE TITLE
Go Vet: JoinVertical already declared through dot-import of package lipgloss

### ISSUE THREAD

**Issue by ocelotsloth** [maaslalani/slides#14]
**Describe the bug**

I went ahead and made an [AUR package](https://aur.archlinux.org/packages/slides/) for this (I'll set some notifications up so that I can maintain the package as you release new versions).

I know you don't have any tests yet--but I wasn't able to include `go test` in the package build because of a vet issue:

> vet: styles/styles.go:31:6: JoinVertical already declared through dot-import of package lipgloss ("github.com/charmbracelet/lipgloss")

Probably not super high on your priority list--but thought I'd bring it to your attention.

Thanks for the cool tool!

**To Reproduce**

```
~/Projects/slides main
❯ go test ./...
# github.com/maaslalani/slides/styles
vet: styles/styles.go:22:6: JoinHorizontal already declared through dot-import of package lipgloss ("github.com/charmbracelet/lipgloss")
?   	github.com/maaslalani/slides	[no test files]
?   	github.com/maaslalani/slides/cmd	[no test files]
?   	github.com/maaslalani/slides/internal/model	[no test files]
```

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: `main`

**Comment by maaslalani** [comment]
> I went ahead and made an AUR package for this (I'll set some notifications up so that I can maintain the package as you release new versions).

Wow thank you so much 🙇 

> Probably not super high on your priority list--but thought I'd bring it to your attention.

Thanks! I'll fix that right now, should be a super quick fix.

> Thanks for the cool tool!

Thanks for using it! Feel free to drop any suggestions on how it can be more useful/better!

**Comment by maaslalani** [comment]
Fixed the `go vet` issue 🙂 with https://github.com/maaslalani/slides/commit/5d89bf2551a51ec22b037b785095943e4c9aed17
