### ISSUE TITLE
Consider respecting `GLAMOUR_STYLE`

### ISSUE THREAD

**Issue by h0adp0re** [maaslalani/slides#142]
It'd be really nice if `slides` respected `GLAMOUR_STYLE` when I'm sure I always want the same styles.

The variable is briefly described here: https://github.com/charmbracelet/glamour#styles

Edit: overriding the theme would need to remain a possibility for individual slideshows.

**Comment by maaslalani** [comment]
Hey, this is definitely a good idea! Thanks so much for creating the issue.

**Comment by maaslalani** [comment]
@h0adp0re https://github.com/maaslalani/slides/pull/146 should respect `GLAMOUR_THEME`, I believe you can set it to `ascii`, `light`, etc... or a file location!

**Comment by maaslalani** [comment]
My fault, fixed: https://github.com/maaslalani/slides/pull/149

**Comment by maaslalani** [comment]
Thank _you_ for using `slides` ❤️
