### ISSUE TITLE
stderr pollutes pre-processing

### ISSUE THREAD

**Issue by knpwrs** [maaslalani/slides#144]
I have graph-easy installed via [whalebrew](https://github.com/whalebrew/whalebrew) on an m1 mac (`whalebrew install tsub/graph-easy`). When I run `echo '[a] -> [b]' | graph-easy --as=boxart` I get the following output:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
┌───┐     ┌───┐
│ a │ ──> │ b │
└───┘     └───┘
```

The warning message is on stderr. If I redirect stderr the warning doesn't appear:

```
❯ echo '[a] -> [b]' | graph-easy --as=boxart 2>/dev/null
┌───┐     ┌───┐
│ a │ ──> │ b │
└───┘     └───┘
```

Consider the following markdown:

    ```
    ~~~graph-easy --as=boxart
    [a] - to -> [b]
    ~~~
    ```

On my machine, that makes a slide which looks like this:

```
     WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
     ┌───┐  to   ┌───┐
     │ a │ ────> │ b │
     └───┘       └───┘


   Ken Powers 2022-03-22                                                                                                                                                   Slide 2 / 2
```

I attempted to redirect stderr, but then I just get an empty slide.

    ```
    ~~~graph-easy --as=boxart 2>/dev/null
    [a] - to -> [b]
    ~~~
    ```

Is there a way to not make stderr show up on my slides?

**Comment by maaslalani** [comment]
Looks like we use `CombinedOutput` which fetches the `stderr` along with the normal `stdout`. I think it's reasonable to change this to only `Output`.

**Comment by maaslalani** [comment]
@knpwrs https://github.com/maaslalani/slides/pull/145 should prevent `stderr` from showing up in the pre-process output! Thanks for reporting this issue.

**Comment by knpwrs** [comment]
Awesome, thank you for the quick fix!

**Comment by maaslalani** [comment]
No problem! Thanks for the well written issue!
