### ISSUE TITLE
Preprocessing blocks not working

### ISSUE THREAD

**Issue by elisiariocouto** [maaslalani/slides#151]
**Describe the bug**
Preprocessing blocks are not working

**To Reproduce**

Run slides with this content:
```
# Hello

This is the first slide.

Showing a graph:

~~~graph-easy --as=boxart
    [ CLI ] - calls -> [ API ]
    [ Human ] -> [ CLI ]
~~~
```
**Expected behavior**
This should render a graph but I only see the text. I tried with other binaries, even a simple `echo "something"` doesn't work.

**Screenshots**
<img width="1018" alt="Screenshot 2022-04-28 at 11 48 46" src="https://user-images.githubusercontent.com/818914/165736722-1da9fa0b-6f29-4971-9aa1-9b57eec8ca6a.png">

**Desktop:**
 - OS: macOS 12.3.1
 - MacBook Pro M1
 - slides 0.8
 - iTerm2 3.5.0

**Comment by maaslalani** [comment]
Hi, there! Is the file executable?

```
chmod +x file.md
slides file.md
```

**Comment by elisiariocouto** [comment]
Ooops. My bad. I though that the executable permission was only needed on "imports". It works if I make my markdown file as an executable. Thank you and keep up the good work.

**Comment by maaslalani** [comment]
No problem! Thanks for using slides, I really appreciate it ❤️
