### ISSUE TITLE
graph-easy example not working

### ISSUE THREAD

**Issue by primalmotion** [maaslalani/slides#154]
Hi, 

I have issue with the output of ~~~ instructions. There don't seem to take into account new lines. The example in the readme with graph-easy produces this

```
~~~graph-easy --as=boxart
[ A ] - to -> [ B ]
~~~
```

![screenshot-2022-04-29-10:10:51](https://user-images.githubusercontent.com/208711/165991400-64bf93af-772f-4d21-80c9-a5aab6658d4a.png)

**Desktop (please complete the following information):**
 - Arch Linux
 - terminal: foot version: 1.12.1 +pgo +ime +graphemes -assertions (but I also tried on alacritty)

**Comment by maaslalani** [comment]
Hi there! Can you wrap the pre-processed code in code blocks and let me know if that solves it for you?

````
```
~~~graph-easy --as=boxart
[ A ] - to -> [ B ]
~~~
```
````

**Comment by primalmotion** [comment]
it does ! Is that how I should do it, or is this a bug?

**Comment by maaslalani** [comment]
That's how it should be done, I think. I will update the README. Thanks!

**Comment by primalmotion** [comment]
cool thanks!
