### ISSUE TITLE
"slides: command not found"

### ISSUE THREAD

**Issue by zevaverbach** [maaslalani/slides#16]
**Describe the bug**
I can't use the CLI command, my system can't find it.

**To Reproduce**
1. Install or upgrade Go on a Mac using homebrew.
2. `go get github.com/maaslalani/slides`
3. make a basic .md file. 
4. `slides basic.md`

**Expected behavior**
I expected the presentation to launch.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 11.2.3

**Additional context**
I'm using `go version go1.16.4 darwin/amd64`

**Comment by k0rn1** [comment]
follow this guide to add go executables  to your `PATH` variable: https://sourabhbajaj.com/mac-setup/Go/

**Comment by maaslalani** [comment]
Hey! In addition to the solution above, you can also just download the macOS binary and then place it in a place where you have your PATH set.

I think soon I will look into adding slides to homebrew and other package managers so you can just install it without Go.

**Comment by maaslalani** [comment]
BTW, you can now install `slides` with Homebrew
```
brew install slides
```
or if you want the latest version
```
brew install --HEAD slides
```
