### ISSUE TITLE
graph-easy rendering broken

### ISSUE THREAD

**Issue by fdziarmagowski** [maaslalani/slides#176]
**Describe the bug**
graph-easy rendering is broken

**To Reproduce**
1. Open one of the examples containing graph-easy 
2. Make the md file executable
3. Run it
4. Slides renders the graph incorrectly:
![image](https://user-images.githubusercontent.com/25754384/183025451-e3e5024c-8d33-45ce-9392-a06cd4b3cb43.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/25754384/183025619-a0d9497a-4323-441c-bc90-249c5eb7fc04.png)

```$ echo "[ A ] - to -> [ B ]" | graph-easy --as=boxart
┌───┐  to   ┌───┐
│ A │ ────> │ B │
└───┘       └───┘
```

**Desktop (please complete the following information):**
 - OS: Linux / Debian Bullseye
 - running slides master and latest
 - Alacritty / GNOME Terminal

**Comment by maaslalani** [comment]
@fdziarmagowski You need to wrap the pre-process in a code block so that it preserves the spacing, I believe the example in the README does this

**Comment by fdziarmagowski** [comment]
@maaslalani ah, so this is the trick! Thanks and sorry for unnecessary noise.

**Comment by maaslalani** [comment]
No problem at all! Thank you for using slides!
