### ISSUE TITLE
What theme are u using?

### ISSUE THREAD

**Issue by JOJ0** [maaslalani/slides#179]
Hi @maaslalani, what glamour theme are you actually using in your demo gif? Is it dracula? I don't get the h2-hX pre-characters I can see in the demo when using the default setting/style of a freshly pip-installed slides package.
Thanks for any hints!

**Comment by maaslalani** [comment]
Hey @JOJ0 I'm using a custom glamour theme: https://github.com/maaslalani/slides/blob/main/styles/theme.json

**Comment by JOJ0** [comment]
Should this be automatically used if no theme is configured in the slides md file?

Is it contained in the latest release on pypi?

**Comment by maaslalani** [comment]
Yes, this should automatically be used if no theme is configured.
I'm unsure about whether it is contained on the latest release of pypi.

**Comment by maaslalani** [comment]
Also, if you are using pip/python, I highly recommend https://github.com/d0c-s4vage/lookatme as an alternative. It should look very similar as I based the colors off of [lookatme](https://github.com/d0c-s4vage/lookatme).
