### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by sibprogrammer** [maaslalani/slides#18]
**Is your feature request related to a problem? Please describe.**
During the preparation of the presentation, I need to restart the program many times.

**Describe the solution you'd like**
Live reload helps to keep one terminal on a separate monitor running the presentation (and refresh it automatically), while editing the Markdown file on another monitor.

**Comment by maaslalani** [comment]
Added my thoughts in the PR, but TLDR I think this should be the responsibility of a different tool. Something like crow, entr, or reflex, I can try to get that working.

**Comment by sibprogrammer** [comment]
I'm also a big fan of Unix Philosophy, but here is not the case ) I can even try to utilize `watch` or `nodemon` for that purpose, but I know that I will end up with context loss due to the relaunch of utility. Of course, it is possible to try to save the internal state (the current slide number) on disk, but it looks like a worse idea.
Anyway `lookatme` and `sli.dev` have this option and I found it quite useful for presentation preparation.

**Comment by maaslalani** [comment]
I was thinking an environment variable like `SLIDES_PAGE` which `slides` would respect. This would be useful when live reloading but also for starting slides at a given page like `SLIDES_PAGE=5 slides presentation.md` and also for scripting, if a user wants to increment the slides every 30 seconds or something. It seems like a flexible solution in my head. What do you think?

**Comment by sibprogrammer** [comment]
> and update when the page changed
I guess it will not work. It's not possible to change the environment variable and make the parent process aware of this change. AFAIK, it's just a copy.
