### ISSUE TITLE
golang code block with tab indent renders wrong

### ISSUE THREAD

**Issue by iampastor** [maaslalani/slides#182]
**Describe the bug**
when render go code block which is indented with tab,  after page next and prev, screen will display wrong

**To Reproduce**
1. go code block below:
````markdown
```go
type A struct {
	a int
	b string
}
```
---
```go
type C struct {
	d []byte
}
```   

````

2. slides this file
3. page next and page prev
4. screen will display wrong

**Expected behavior**
screen display right

**Screenshots**
golang code block md

<img width="321" alt="image" src="https://user-images.githubusercontent.com/4197888/185956180-1fd4667d-707b-44cb-ad98-4b1564b2bf4f.png">

slide 1
<img width="175" alt="image" src="https://user-images.githubusercontent.com/4197888/185956543-c36bd1aa-3bed-42f1-9103-f1ccc5e6c71b.png">

slide 2
<img width="169" alt="image" src="https://user-images.githubusercontent.com/4197888/185956590-4bf2d768-7c37-4a90-bb0b-b59390188fc9.png">

slide 1 prev

<img width="152" alt="image" src="https://user-images.githubusercontent.com/4197888/185956639-b2ff5d35-8e1c-48bc-9a71-13286a0839b3.png">

**Desktop (please complete the following information):**
 - OS: Darwin amd64

**Comment by ankush** [comment]
I can validate this too. Subsequent slides show duplicate heading/footer lines.

**Comment by maaslalani** [comment]
Hmmm, I can also reproduce. It has something to do with the indentation. When I replace the indentation with 2 spaces the problem goes away.

**Comment by crl-n** [comment]
This also happens with C as the language. I was using this code

```c
#include <stdio.h>

int	main(void)
{
	puts("Hi");
	return (0);
}
```

**Comment by maaslalani** [comment]
#200 should fix these issues!

**Comment by maaslalani** [comment]
@iampastor @crl-n These changes are now on `main`, let me know if this fixes it for you! Thank you for reporting this issue ❤️
