### ISSUE TITLE
The serve command returns "could not read file"

### ISSUE THREAD

**Issue by hmngwy** [maaslalani/slides#188]
**Describe the bug**
the serve command returns the below 

```
Error: could not read file
Usage:
  slides <file.md>
```

the file is fine, it runs with `slides temp.md`

**To Reproduce**
1. `yay -Syu slides`
3. `slides serve temp.md`

**Expected behavior**
should serve the slides over ssh 

**Screenshots**
refer to description

**Desktop (please complete the following information):**
 - OS: Arch
 - Version 5.19.3-arch1-1

**Comment by maaslalani** [comment]
Hey! Apologies, the `slides serve` command is available only on `main` not the latest release. I will make a new release but in the mean time you can install the latest code on `main`.

**Comment by maaslalani** [comment]
0.9.0 is released and should have the `slides serve` command working!
