### ISSUE TITLE
Mathematics support.

### ISSUE THREAD

**Issue by nations-Xiong** [maaslalani/slides#20]
If add support for mathematics would be wonderful!

**Comment by maaslalani** [comment]
Hey there for mathematics, do you mean support for things like LaTex? Or do you mean support for evaluating math expressions?

**Comment by 4y8** [comment]
If you want support for mathematical formatting, an option would be to [eqn](https://en.wikipedia.org/wiki/Eqn_(software)) with ascii output and print it. However, that would add a dependency. Something similar may exist for latex.

**Comment by nations-Xiong** [comment]
Yeah, support for latex.

**Comment by maaslalani** [comment]
As a heads up, I'm thinking about add Generic preprocessing: https://github.com/maaslalani/slides/pull/55

So you could probably have a command that converts your latex to ascii and render it out with that 😄

**Comment by maaslalani** [comment]
Going to close this since I believe the essence of this can be solved through the pre-processing feature and https://linux.die.net/man/1/tex2mail or equivalent LaTeX to ASCII program:

```markdown
# slides.md
~~~tex2mail ...
\frac{1}{2} = \sqrt{2}x
~~~
```
