### ISSUE TITLE
Slide delimiter not working as expected

### ISSUE THREAD

**Issue by srikkant** [maaslalani/slides#207]
**Describe the bug**
`---` does not split the content into multiple slides. Instead, I see the content like the screenshot below. I see `------` where slide must have ended

**Expected behavior**
The content should be separated into different slides.

**Screenshots**
This is what I see when I open slides.
![image](https://user-images.githubusercontent.com/16999836/212728108-f5adb6de-466f-4eba-94d9-1422deefa497.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Installed through go install on 16th January.

**Comment by chrisvanmeer** [comment]
Could you provide a raw snippet of your markdown file?

**Comment by srikkant** [comment]
Yup, I just used the example here in this repo - https://github.com/maaslalani/slides/blob/main/examples/slides.md

**Comment by maaslalani** [comment]
@srikkant I have a suspicion that this might be due to line endings and the differences on MacOS vs Windows, can you try two things:

1. Create a slides file from scratch so that it uses line endings for windows
2. Run: `curl https://raw.githubusercontent.com/maaslalani/slides/main/examples/slides.md | slides` so that the line endings do not change

**Comment by srikkant** [comment]
@maaslalani  Thanks a ton! You were absolutely correct. 
FYI, added a editorconfig to my project root with the correct line endings and it all works beautifully.  
Also, came to this project through your talk at neovimconf. Having a lot of fun trying out the tools you have worked on, great job and thanks for all of those as well!

**Comment by maaslalani** [comment]
@srikkant Awesome! Glad to hear this! Thank you so much ❤️
