### ISSUE TITLE
Julia support

### ISSUE THREAD

**Issue by IgorDouven** [maaslalani/slides#208]
I tried to execute Julia code on a slide, but that printed an error message on the slide, saying 'unsupported language'. Maybe I'm mistaken but from the documentation it looks like Julia should be supported. Am I doing something wrong?

**Comment by c0dehu1k** [comment]
@IgorDouven Can you send me sample md file which is not working?
Below works for me
 
```
## Code execution
```Julia
"Hello World"
```
```

**Comment by c0dehu1k** [comment]
@IgorDouven Its works for me. Please paste sample md file if you still encounter issue
Please watch out for lower and uppercase "J". It should be lower case.

![Screenshot](https://ibb.co/4wyqYFY)

**Comment by c0dehu1k** [comment]
@maaslalani We can close this.
