### ISSUE TITLE
Add support for an embedded terminal

### ISSUE THREAD

**Issue by MikaelFangel** [maaslalani/slides#216]
**Is your feature request related to a problem? Please describe.**
When doing presentations I would like show of things in vim or other interactive cli programs.

**Describe the solution you'd like**
I would like a option to add a embedded terminal window in a slide. It could be like the one in lootatme.

**Describe alternatives you've considered**
The alternatives I've considered is changing to lookatme or as of now I'm just using tmux to split the window.

**Additional context**
No additional context.

Thanks for a great program! 🙌🏻

**Comment by maaslalani** [comment]
Hey, I really recommend using `tmux` for this one:

Likely `tmux display-popup` will help here:

````
# Embedded Terminal

This is a test:

```bash
tmux display-popup
```

---

# Embedded Terminal

Another test

```bash
tmux display-popup confetty
```
````

**Comment by maaslalani** [comment]
https://user-images.githubusercontent.com/42545625/221008276-2eb0f9ee-f3ec-4c44-a3f4-e8480944ac54.mov

**Comment by MikaelFangel** [comment]
Thanks! I'm quite new to tmux so I didn't know about the pop-up feature. Will use this in the furture.

**Comment by maaslalani** [comment]
I actually just learned about the feature today! And I've been using tmux for a while 😄

**Comment by MikaelFangel** [comment]
Have played with for some time now, and if you want to open vim in a popup and not close the popup on ESC. You can run the command `tmux display-popup -E 'vim'`. Just thought I would let you know.

**Comment by maaslalani** [comment]
Awesome! Thanks so much for letting me know that trick! ❤️
