### ISSUE TITLE
ArchLinux - Failed to install

### ISSUE THREAD

**Issue by rlopzc** [maaslalani/slides#219]
**Describe the bug**

**To Reproduce**
1. `yay -S slides`

**Expected behavior**
Slides is installed

**Desktop (please complete the following information):**
 - OS: Arch
 - Version Kernel: 6.1.14-1-lts

**Additional context**
Logs:
```
romarin ~ λ yay -S slides
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  slides-0.9.0-1

  1 slides                           (Build Files Exist)
...
:: (1/1) Parsing SRCINFO: slides
==> Making package: slides 0.9.0-1 (sáb 04 mar 2023 07:17:28)
==> Retrieving sources...
  -> Updating slides git repo...
==> Validating source files with sha256sums...
    slides ... Skipped
==> Making package: slides 0.9.0-1 (sáb 04 mar 2023 07:17:29)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating slides git repo...
==> Validating source files with sha256sums...
    slides ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of slides git repo...
Cloning into 'slides'...
done.
Switched to a new branch 'makepkg'
==> Sources are ready.
==> Making package: slides 0.9.0-1 (sáb 04 mar 2023 07:17:30)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go: clean -testcache cannot be used with package arguments
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: slides
```

**Comment by ocelotsloth** [comment]
Hey @rlopzc I packaged this on the AUR; I'll take a look at this.

**Comment by ocelotsloth** [comment]
Try it again; looks like the go cli changed what args are valid there.

I just updated the `slides` package, working on fixing `slides-git`:
  - https://aur.archlinux.org/cgit/aur.git/commit/?h=slides&id=abdf11e531b172a66207e1fb4e39791e221013e9

Ref:
  - https://github.com/golang/go/issues/53725
  - https://github.com/evanw/esbuild/commit/4e53c2783b460f79b01e3d7ea9455a97a69eb269

**Comment by ocelotsloth** [comment]
Ok, `slides` and `slides-git` are both fixed. `slides-bin` should be unaffected since it doesn't actually build the software.

Can you confirm you're able to install `slides` now with 0.9.0-2 on the AUR?

**Comment by rlopzc** [comment]
It is fixed!

I opened the `slides` commmand, is working, but the graphs look like this:
![image](https://user-images.githubusercontent.com/6199588/222905881-ae785a05-57a4-4609-8b26-1c0a4c275fde.png)

How can I fix them?

**Comment by ocelotsloth** [comment]
Awesome!

Afraid I'm not going to able to be much help with the graph issue since I don't really know what it's supposed to look like. A new issue should help find somebody who does know.
