### ISSUE TITLE
Output from preprocessed commands gets squashed

### ISSUE THREAD

**Issue by WilliamBehrens** [maaslalani/slides#239]
**Describe the bug**
If have a line like
```md
~~~graph-easy
[a]->[b]
~~~
```
The output when displayed is forced all on one line.

**Desktop:**
 - OS: Linux (NixOS)
 - Version: latest in nixpkgs, `slides --version` provides no information.

**Comment by maaslalani** [comment]
Please try wrapping the pre-process in code blocks to preserve whitespace / new lines.

````
```
~~~graph-easy
[ A ] -> [ B ]
~~~
```
````

**Comment by WilliamBehrens** [comment]
That fixed the issue.
