### ISSUE TITLE
Go Install fails to install on Fedora

### ISSUE THREAD

**Issue by Jonathan-Zollinger** [maaslalani/slides#252]
**Describe the bug**
I'm unable to install slides via the documented instructions for go

**To Reproduce**

 _see [environment](#environment) for os and software versions_

1. call `go install github.com/maaslalani/slides@latest`

<a id='environment '><details><summary>Environment</a></summary>

### Go version
 `go version go1.20.4 linux/amd64`

### Terminal
```
 kitty --version
kitty 0.28.1 created by Kovid Goyal
```

### OS
`Fedora 38`
(i3 wm if that makes a difference)

<details><summary>/etc/os-release</summary>

```
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
``` 

</details>
</details>

**Expected behavior**
slides is installed after calling the appropriate installer command

<a id="error-output">**error output**</a>
```
 go install github.com/maaslalani/slides@latest
go: downloading github.com/muesli/termenv v0.12.1-0.20220615005108-4e9068de9898
go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.1-0.20220623121936-ca32c4c62873/screen.go:7:2: github.com/muesli/termenv@v0.12.1-0.20220615005108-4e9068de9898: invalid version: unknown revision 4e9068de9898
```

**Additional context**
see [environment](#environment) .

the [output](#error-output) from the install attempt seems to be an issue with the termenv dependency, whether the versioning is off or the termenv installer is bad (or something else) I dunno.

**Comment by maaslalani** [comment]
Hey @Jonathan-Zollinger can you try again with:

```
go install github.com/maaslalani/slides@main
```

**Comment by Jonathan-Zollinger** [comment]
Hi @maaslalani, that worked great! do you want me to close this? I feel bad this was such a simple fix, but I'm glad it didn't take much on your end.

**Comment by ntonnaett** [comment]
It would be really nice to have a new release including that fix.
