### ISSUE TITLE
Support Inline HTML

### ISSUE THREAD

**Issue by mutairibassam** [maaslalani/slides#31]
Since Markdown doesn't support color, you go with inline HTML as an alternative. I've tried to write inline HTML in the slide file as the below snapshot.

<img width="675" alt="code" src="https://user-images.githubusercontent.com/54819958/122552454-01fff200-d03f-11eb-87fa-dc6402c5155e.png">

but the output shows the text with no color. Please see the output in the below snapshot.

<img width="368" alt="output" src="https://user-images.githubusercontent.com/54819958/122552608-3378bd80-d03f-11eb-9cb6-ba40689a2650.png">

**Comment by roelsprimont** [comment]
To me this seems more like a feature request for [Glamour](https://github.com/charmbracelet/glamour), which slides uses to render the markdown.

**Comment by maaslalani** [comment]
Agree with @roelsprimont, I think this functionality wouldn't live in slides. I'm also fairly sure that glamour does not want to implement HTML parsing as well.

**Comment by mutairibassam** [comment]
I really liked the simplicity in slides and this is why I am asking for this feature. I believe if I can add specific colors for specific words, it would be crazy!

**Comment by maaslalani** [comment]
Thanks @mutairibassam!

Have a look at https://github.com/maaslalani/slides/blob/main/styles/theme.json

`slides` allows you to pass your own `theme.json`, I see theres `html_block` and `html_span` maybe you can change those values to change the colour of things? If you're willing to give up bold, italics, underline, or strike through, you can also change those styles to whatever colour you want. I know its not exactly what you're asking for here, but it could work if you only want a limited number of colours.
