### ISSUE TITLE
PlantUML ASCII Art diagram integration?

### ISSUE THREAD

**Issue by boldandbusted** [maaslalani/slides#36]
I'd love to see integration with PlantUML's ASCII Art diagram output. :)

Reference: https://plantuml.com/ascii-art

Thank you for this nifty application! :) Cheers.

**Comment by maaslalani** [comment]
Hey! This is a really cool program, thanks for introducing me to it. I plan on having some sort of preprocessing mechanism for converting things like graphviz, ascii images, :emojis:, and stuff like this. For now though, you can probably just copy and paste the ascii stuff directly inside the slides 😄

**Comment by maaslalani** [comment]
Closing in favour of https://github.com/maaslalani/slides/issues/51
