### ISSUE TITLE
Code block without trailing new line can't be executed

### ISSUE THREAD

**Issue by suzaku** [maaslalani/slides#39]
**Describe the bug**

Code block without trailing new line can't be executed.
When I click CTRL + e, I see the error `Error: could not parse code block`.

**To Reproduce**

Add a code block to the end of the last slide without adding a trailing new line.

**Expected behavior**

Since Markdown doesn't have a problem to parse this kind of code block, I would expect the code block to be runnable.

**Comment by maaslalani** [comment]
Ahh interesting, thanks for reporting this. I will try to reproduce and fix, this is probably a bug in the regex

**Comment by maaslalani** [comment]
We might be able to take out the new line at the end from the regex here: https://github.com/maaslalani/slides/blob/main/internal/code/code.go

**Comment by suzaku** [comment]
Yes, that's an easy way to fix the problem. Maybe replace it with something like `\s?`?
