### ISSUE TITLE
Why j shotcut goes up?

### ISSUE THREAD

**Issue by lobre** [maaslalani/slides#40]
A small comment/question regarding keyboard shortcuts `j` and `k`.

Maybe I am mistaken, but to me, those two shortcuts became well-known thanks to vim. In vim, `j` means going to the **next** line, while `k` is to go **back up**.

Why this choice of saying that `j` goes to the previous slide and `k` to the next one? It seems odd to me. In most presentation applications, the opposite is implemented.

Thanks

**Comment by infinity532** [comment]
Hi in which you are working for ? What's the project

**Comment by maaslalani** [comment]
Ahh looks like just an oversight, I will switch them :)

**Comment by infinity532** [comment]
Send me website tho.
