### ISSUE TITLE
Markdown block in example is rendered incorrectly

### ISSUE THREAD

**Issue by koljakube** [maaslalani/slides#42]
**Describe the bug**
The markdown block at the end of `examples/slides.md` should be on one slide. Instead it is split at the `---` inside the block.

**To Reproduce**
Check out
1. Clone this repository
2. Run `slides examples/slides.md` inside of it
3. Go to the end of the presentation
4. On page 8 the second half of the code block is rendered as a new page

**Additional context**
If slides has a `--version` argument, I can't find it.

**Comment by maaslalani** [comment]
Did you modify the `example/slides.md` file? There is a trailing space to prevent the split from happening, perhaps you saved the file and your editor removes trailing spaces?

**Comment by maaslalani** [comment]
Can you reproduce like this?
```
curl https://raw.githubusercontent.com/maaslalani/slides/main/examples/slides.md | go run main.go
```

**Comment by koljakube** [comment]
Welp, sorry for wasting your time, you are right. I must have accidentally removed the spaces and didn't check the git status before writing here.

**Comment by maaslalani** [comment]
It's all good! I really appreciate you taking the time to write the issue! And super glad you're checking out / using the tool 😄 Always feel free to create issues and point things out 🙂
