### ISSUE TITLE
Automatic new page after code-block

### ISSUE THREAD

**Issue by ChristopherLenz** [maaslalani/slides#47]
**Describe the bug**
After inserting a code-block it is not possible to add more text. A code-block adds automatically a new page (`---`). If you add `---` after a code-block this will add an empty page.

**To Reproduce**
1. Create a file with the example from the Readme: https://github.com/maaslalani/slides#readme
2. Start the slide
3. browse to the code-block
4. See issue

Example from screenshot
```
## Everything happens in your terminal
Create slides and present them without ever leaving your terminal.

---

## Execute code blocks
Press `ctrl+e` on a slide with a code block to execute it
Slides with display the output at the end of the slide.

~~~go
package main

import "fmt"

func main() {
  fmt.Println("Hello, world!")
}
~~~

Text after Code-Block

---

## Bash

~~~bash
ls -al
~~~
---

```

**Expected behavior**
A code-block will not automatically add a new page

**Screenshots**
![image](https://user-images.githubusercontent.com/11405586/123398069-6bce4d80-d5a3-11eb-920b-7fef32bb7685.png)

![image](https://user-images.githubusercontent.com/11405586/123398110-77217900-d5a3-11eb-9a74-a3e2035f23df.png)

**Desktop (please complete the following information):**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Software version**
snap-id:      iVzf6DoBLkUj1lmBkm6cKA545qHx42nK
tracking:     latest/stable
refresh-date: today at 10:12 CEST
channels:
  latest/stable:    0.3.0 2021-06-24 (11) 6MB -
  latest/candidate: ↑                         
  latest/beta:      ↑                         
  latest/edge:      0.3.0 2021-06-24 (11) 6MB -
installed:          0.3.0            (11) 6MB -

**Comment by maaslalani** [comment]
Ah sorry about that `~~~` used to be the delimiter for new pages and when we changed it it `---` we kept the old old around for backwards compatibility.

Can you try using three backticks instead of `~~~` for your code blocks for now?

I will remove `~~~` as a delimiter for new pages soon.

**Comment by maaslalani** [comment]
Thanks for the super well written issue btw! Very much appreciated! ❤️

**Comment by ChristopherLenz** [comment]
Thanks. That fixed it. Shall I close the issue or want you to leave it open until the backwards compatibility is removed and the readme is updated?
