### ISSUE TITLE
[feature]Code execution with Node.

### ISSUE THREAD

**Issue by JasonkayZK** [maaslalani/slides#57]
**Is your feature request related to a problem? Please describe.**
As Python, Ruby is supported, why not Node for javascript?

**Describe the solution you'd like**
For those frontend developers, probably they do not set the python or ruby environment, but Node.js is definitely set!
So, why not Node.js?
And also, javascript is an easy script program, for demo, you know.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Let's say:

```markdown
### Node

``javascript
console.log('hello');
``
```

**Comment by maaslalani** [comment]
Hey! This is a great idea, do you want to try implementing this? It will look a lot like https://github.com/maaslalani/slides/pull/38. If not, I can implement it quickly :)

But thanks for the good idea, I just forgot about node.

**Comment by JasonkayZK** [comment]
Sorry for getting up late. 😭 
It seems that slides has already supported Node.js.
Awesome, thanks! ❤️

**Comment by maaslalani** [comment]
Hahah! All good! If there's any other languages you want to add please feel free to 😄
