### ISSUE TITLE
Pre release 0.4.0 fails tests

### ISSUE THREAD

**Issue by ocelotsloth** [maaslalani/slides#60]
**Describe the bug**
Tests on the pre-release 0.4.0 tag fail.

```
~/Projects/aur/slides-git/src/slides main
❯ go test ./...
?   	github.com/maaslalani/slides	[no test files]
?   	github.com/maaslalani/slides/cmd	[no test files]
ok  	github.com/maaslalani/slides/internal/code	(cached)
ok  	github.com/maaslalani/slides/internal/file	(cached)
ok  	github.com/maaslalani/slides/internal/meta	(cached)
?   	github.com/maaslalani/slides/internal/model	[no test files]
--- FAIL: TestExecute (0.00s)
    --- FAIL: TestExecute/Replace (0.00s)
        execute_test.go:34: Invalid execution, want Replace, got 
FAIL
FAIL	github.com/maaslalani/slides/internal/process	0.001s
ok  	github.com/maaslalani/slides/styles	(cached)
FAIL
```

**To Reproduce**

```
git clone https://github.com/maaslalani/slides.git
cd slides
git checkout main
git pull
go test ./...
```

Alternatively, on Arch Linux:

```
git clone https://aur.archlinux.org/slides-git.git
cd slides-git
makepkg
```

Yields:

```
~/Projects/aur/slides-git master*
❯ makepkg
==> Making package: slides-git 0.4.0.r0.g742251d-1 (Sun 27 Jun 2021 09:40:40 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating slides git repo...
Fetching origin
From https://github.com/maaslalani/slides
 - [deleted]         (none)     -> node
 - [deleted]         (none)     -> preprocess
 - [deleted]         (none)     -> preprocessing
==> Validating source files with sha256sums...
    slides ... Skipped
==> Extracting sources...
  -> Creating working copy of slides git repo...
Switched to and reset branch 'makepkg'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
==> Starting check()...
?   	github.com/maaslalani/slides	[no test files]
?   	github.com/maaslalani/slides/cmd	[no test files]
ok  	github.com/maaslalani/slides/internal/code	(cached)
ok  	github.com/maaslalani/slides/internal/file	0.002s
ok  	github.com/maaslalani/slides/internal/meta	(cached)
?   	github.com/maaslalani/slides/internal/model	[no test files]
--- FAIL: TestExecute (0.00s)
    --- FAIL: TestExecute/Replace (0.00s)
        execute_test.go:34: Invalid execution, want Replace, got 
FAIL
FAIL	github.com/maaslalani/slides/internal/process	0.001s
ok  	github.com/maaslalani/slides/styles	(cached)
FAIL
==> ERROR: A failure occurred in check().
    Aborting...
```

**Expected behavior**
Tests pass.

**Desktop (please complete the following information):**
 - OS: Arch Linux `5.12.12-arch1-1`
 - Golang: `go version go1.16.5 linux/amd64`

**Comment by ocelotsloth** [comment]
Ah ok looks like I need a testing dependency https://github.com/chmln/sd

**Comment by maaslalani** [comment]
Ahh yes sorry about that, I need to figure out testing dependencies to use less of them haha. Are you able to use `go test ./... -short` the `-short` flag skips the tests that need dependencies.

**Comment by maaslalani** [comment]
Also thanks so so so much for maintaining the AUR package ❤️

**Comment by ocelotsloth** [comment]
Not too difficult to add that dependency -- `sd` is actually [in the community repository](https://archlinux.org/packages/community/x86_64/sd/) so it doesn't even add an AUR dependency.

That said--if you're interested in #61 it replicates the spirit of the test without the added dependency. Up to you if you want to switch that or just have me add a build dependency.

**Comment by maaslalani** [comment]
#61 Looks good! I will merge that

**Comment by maaslalani** [comment]
Do I need to add the commit to the release or can you build the package from `main`?

**Comment by ocelotsloth** [comment]
On Sun, Jun 27, 2021, at 10:17 PM, Maas Lalani wrote:
> Do I need to add the commit to the release or can you build the package 
> from `main`?

It builds from the tag so you’ll need to push a new release in order for arch users to build without disabling checks.

The slides-bin and slides-git builds would both be fine. The former has no tests (just downloads the binary you publish) and the latter already has the fix.
