### ISSUE TITLE
Lua support for code block execution

### ISSUE THREAD

**Issue by marcotrosi** [maaslalani/slides#75]
I think the title is pretty self-explanatory.
slides has this wonderful feature of being able to execute code by pressing Ctrl-e (and syntax highlighting).
And I tried it with Lua and I got the message "unsupported language" and so I thought I could ask if adding Lua support would be possible.
Thank you very much for considering it.
all the best to you

marco

**Comment by maaslalani** [comment]
Of course, adding it now!

**Comment by maaslalani** [comment]
Thanks for submitting this issue, `Lua` support is added! Should be on `HEAD` now 😄
