### ISSUE TITLE
preprocessing slides using figlet and boxes does not work

### ISSUE THREAD

**Issue by marcotrosi** [maaslalani/slides#78]
Not sure if it's a bug or if I'm doing something wrong.

**Describe the bug**
The slides README shows an example of pre-processing slides with *graph-easy*. According to the description the text is send to the given command as stdin and then replaced in the slide. For *figlet* and *boxes* I was not able to get this to work. I don't know if there are more tools where it doesn't work.

**To Reproduce**
create a slide with the following code block

```
~~~figlet
foobar
~~~
```

or use *boxes* instead of *figlet*.

**Expected behavior**
I would expect that the text gets replaced with the *figlet* or *boxes* output, 
like this ...
![image](https://user-images.githubusercontent.com/8596795/124985519-cacba200-e03a-11eb-933a-f0fb0f4499ea.png)

but the text stays as it is ... (left side the slide in presentation mode)
<img width="487" alt="figlet fail" src="https://user-images.githubusercontent.com/8596795/124986141-93a9c080-e03b-11eb-875e-f2646b7beca0.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.14

**Comment by maaslalani** [comment]
Hey, this definitely looks correct! What version of `slides` are you on? This feature was introduced in `v0.4.0`

Also, does all pre-processing not work? Can you do a simple:
```
~~~echo hello
should be erased
~~~~
```

Also, does your file have execution permissions? `chmod +x file.md`. This is needed for security reasons since this executes code on your system so the file must be executable to ensure you've opted-in to pre-processing.

**Comment by maaslalani** [comment]
This is a great use-case of pre-processing though! Thanks for using slides! 😄

I suspect you are just missing the `chmod +x slides.md`

**Comment by maaslalani** [comment]
It works for me! (with the file being executable)

![image](https://user-images.githubusercontent.com/42545625/125011190-f4ce9580-e035-11eb-8843-c9f958f16a83.png)

**Comment by marcotrosi** [comment]
Thanks again for the fast reaction time and for sharing slides with the world.

Okay, it works now. Thank you so much.

Of course it was my fault. I had used `chmod 754 slides.md` instead of `chmod +x slides.md`. I thought it should be enough when I (the owner) or my group have execution rights, but it's the "others" that need it.

One more side note...
The example in the README.md or preprocess.md shows only the 3 tilde before and after. But according to the example above and also when looking at your markdown examples in RAW format, I can that also the 3 backticks before and after are required, otherwise slides prints a bunch of dashes right before the replaced text.
I assume that GitHub is removing the 3 backticks when rendering these markdown files here. Maybe you can add a sentence that mentions that the 3 backticks before and after are required but GitHub doesn't show them properly.
