### ISSUE TITLE
Example markdown slide render issue around `~~~`

### ISSUE THREAD

**Issue by CosmosAtlas** [maaslalani/slides#83]
**Describe the bug**
When testing with the example markdown slide provided in readme, there is a render issue with the box art slide.

**To Reproduce**
run `slides file.md` where `file.md` contains the example markdown slide.

**Expected behavior**
Should render correctly

**Screenshots**
![](https://i.imgur.com/HhxRxC3.png)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Version [Latest github on commit `982bc2725a50307d0adc2b215b986154368e028a`]

**Side note**

The readme still have `j` moving to previous and `k` moving to next.

**Comment by maaslalani** [comment]
Hey! Do you have graph-easy and GraphViz installed btw? Does all pre-processing fail or just this specific example

**Comment by CosmosAtlas** [comment]
Sorry if I conveyed the wrong idea. But the issue I'm reporting is not related to the code block section that follows. 

If you look carefully at where it breaks, it's actually unrelated to whether graph-easy is in place. Actually, just by removing the `~~~` as shown in vim on line 34, it works completely fine. : )

**Comment by mmm0171** [comment]
0xa36fD8fF0524f287422337d99bABdf05923f581B

**Comment by maaslalani** [comment]
I removed the `~~~` in the slide on line 34 as you shown in vim. Not a permanent fix but should be okay for now.
