### ISSUE TITLE
feature request: less metadata on the bottom

### ISSUE THREAD

**Issue by raidancampbell** [maaslalani/slides#87]
**Is your feature request related to a problem? Please describe.**
I would like to have less text shown on the slides in a presentation: I don't need my name on every slide, and the people watching the presentation are (hopefully) aware of today's date.

**Describe the solution you'd like**
Ideally I would like to have the option to pass a `--no-author`, `--no-date`, or `--no-page` flag on startup.

**Describe alternatives you've considered**
Adding additional support in the `metadata` portion would suffice.  This approach would keep the CLI invocation clean at the cost of coupling the preferences of a presentation with the presentation itself.

**Additional context**
I don't plan on needing these features for another month. If you have an appetite for the feature, I'd be happy to make the change myself

**Comment by maaslalani** [comment]
This sounds good! We have a metadata section where you can pass options (currently only theme) before slides. We could do something like:

```
---
theme: foo.json
author: 
date:
---
```

That way people can specify their own author and dates. And we can default to the current user and current date but you can also leave them empty to hide them (or maybe a key word like `hidden` etc...)

**Comment by cuducos** [comment]
> Would you be interested in adding these author and date metadata options?

If @raidancampbell is not, I am. If you have any roadmap in mind, I'd love to go through it. Otherwise, I can try to come up with something : )

**Comment by raidancampbell** [comment]
@cuducos it looks like you've got a good idea going with #92: if you want to pick this up along the way, be my guest.  Otherwise I'll make some changes for this within the next week

**Comment by maaslalani** [comment]
> If you have any roadmap in mind, I'd love to go through it

No roadmap, there are development docs / contributing docs in the project though, mainly changes should be backwards compatible. In this case, all slides should pretty much look the same unless they specify the `author`/`date` metadata, and everything should be optional including the entire metadata slide itself.
