### ISSUE TITLE
Number lists don't respect starting number

### ISSUE THREAD

**Issue by raidancampbell** [maaslalani/slides#88]
**Describe the bug**
First number in numbered lists isn't respected and always defaults to 1.

**To Reproduce**
The following markdown block will print a numbered list on slide two beginning with the number 1
```markdown
# number values in list ignored
1. one
2. two
4. four (`3.` is expected with most/all markdown processors)

---
# A Continuation
5. five
6. six
```

**Expected behavior**
The second slide's number list in `slides` should match the word beside it

**Screenshots**
![image](https://user-images.githubusercontent.com/5506073/128296018-91ccbfc6-3117-4b8d-b07b-34ebb20152ea.png)
![image](https://user-images.githubusercontent.com/5506073/128295984-08f1750f-1b51-4cff-bee2-610142042e4f.png)

This may be a problem with [goldmark](https://github.com/yuin/goldmark), but they swear they're complaint with commonmark, and commonmark's [reference implementation respects it](https://spec.commonmark.org/dingus/?text=4.%20four%0A5.%20five%0A%0A)

**Comment by maaslalani** [comment]
We use https://github.com/charmbracelet/glamour to render markdown but I think this occurs because the rendering happens at a slide-by-basis. I.e. each slide is an independent markdown document.

**Comment by raidancampbell** [comment]
Ah, I saw `goldmark` and didn't look any further.  As far as I can tell, it's standard across most markdown editors that numbered lists will respect the first number, then ignore all subsequent numbers and iterate by one.
the github-flavored markdown editor handles it like below:
![image](https://user-images.githubusercontent.com/5506073/128444507-b2da5376-754e-4e35-abf0-ad19444e9981.png)

4. four
5. five
1. one

That being said, it's definitely not a bug in `slides`: I'll poke glamour and see if I can replicate it
