### ISSUE TITLE
digraph not being displayed

### ISSUE THREAD

**Issue by Skarlso** [maaslalani/slides#89]
Tried the digraph example and the graph isn't rendering at all.

https://github.com/maaslalani/slides/blob/main/examples/slides.md

**Desktop (please complete the following information):**
 - OS: OSX 11.4 Big sur
 - Browser ???? this is a terminal tool
 - Version No idea, the command doesn't have a version command.

It only displays the content As is instead of the Graph.

**Comment by maaslalani** [comment]
Can you try this example. https://github.com/maaslalani/slides/blob/main/examples/preprocess.md. The digraphs are a feature of pre-processing. You will need to copy this text to a local file and make it executable with `chmod +x preprocess.md`. You will also need `GraphViz` and `graph-easy` installed.

**Comment by Skarlso** [comment]
Oh, so sorry, I didn't really realise that. I will try.

**Comment by Skarlso** [comment]
Would you mind linking me to these tools, I'm absolutely oblivious. :D

**Comment by maaslalani** [comment]
https://graphviz.org/download/
https://metacpan.org/pod/Graph::Easy

**Comment by Skarlso** [comment]
Thanks!

**Comment by tymbaca** [comment]
Hey! I have GraphViz and graph-easy installed. But still cannot figure out how to use digraph. `https://github.com/maaslalani/slides/blob/main/examples/preprocess.md` doesn't provide any example with digraph...
