### ISSUE TITLE
Executable Code Blocks

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/slides#9]
It would be neat to have live code demos where someone can write a markdown code block and execute it on the slide (by hitting a shortcut) and we can display the result and how long it took to execute.

**Comment by brittonhayes** [comment]
I think ya might be able to leverage something like this to execute code in your slides.

They have an extension for parsing out fenced codeblocks here:
https://github.com/gomarkdown/markdown#extensions

Lots of ways you could approach it but I think that in combination with something like:

```go
file, err := ioutil.TempFile("temp", "slides-exec.*.go")
if err != nil {
    log.Fatal(err)
}
defer os.Remove(file.Name())

output, _ := exec.Command("go", "run", file.Name()).CombinedOutput()

fmt.Println(output)
```
And you could create a temp file to execute then cleanup afterwards etc etc. Would definitely get a bit more complicated when you want to exec different languages.

**Comment by maaslalani** [comment]
Interesting, I have a WIP branch that does the parsing with a regex and also parses the language and runs that against the executable. The main issue will be displaying the result nicely

**Comment by brittonhayes** [comment]
Awesome! Excited to see that branch once ya push it out. Could be a really neat feature that really sets it apart from conventional slide deck options.

**Comment by maaslalani** [comment]
![image](https://user-images.githubusercontent.com/42545625/121791062-c3d47f80-cbb3-11eb-806a-9ae5d6a9fa98.png)

After pressing <kbd>e</kbd>

![image](https://user-images.githubusercontent.com/42545625/121791065-d18a0500-cbb3-11eb-9416-cfa78129bf09.png)
