### ISSUE TITLE
Vim-like navigation

### ISSUE THREAD

**Issue by maaslalani** [maaslalani/slides#96]
Add key bindings to navigate around the presentation with additonal vim bindings:
- <kbd>G</kbd> go to last slide
- <kbd>gg</kbd> go to first slide

**Comment by marcotrosi** [comment]
or one step further and having a config file in home dir (~/.slides) where you can configure whatever you want. keybindings, default color themes that can be overwritten per presentation, ...

**Comment by marcotrosi** [comment]
ah and 13G to go to slide 13, like in Vim to put the cursor on line 13 with 13G.

**Comment by maaslalani** [comment]
> and 13G to go to slide 13, like in Vim to put the cursor on line 13 with 13G.

Ahhh this is a really great idea, and 4j goes 4 slides ahead, etc...

**Comment by maaslalani** [comment]
> or one step further and having a config file in home dir (~/.slides) where you can configure whatever you want. keybindings, default color themes that can be overwritten per presentation, ...
> 
> Not sure if I like the idea myself, maybe it bloats slides unnecessary too much
> 
> 

Yea I would avoid this, I don't want slides to have any persistent configuration on the user's machine (unless theres a really good reason to). Right now all the config lives inside each presentation markdown file, which I think is really nice.
