### ISSUE TITLE
Metadata does not display when set.

### ISSUE THREAD

**Issue by blu3beri** [maaslalani/slides#98]
**Describe the bug**
Metadata does not display in the bar

**To Reproduce**
1.
```sh
brew install slide
```
2. Copy and paste the example metadata file
3. Nothing changes

**Expected behavior**
Metadata should be displayed

**Desktop (please complete the following information):**
 - OS: OS11 - Big Sur
 - iTerm2

**Comment by maaslalani** [comment]
Hey! Sorry about the confusion but this feature was added recently so its only available if you clone and build the project from source. I haven't made a release yet that includes it / released it to homebrew.

You may be able to use
```
brew install slides --HEAD
```
to get the latest I believe. I'd love for you to try and and let me know if everything works as expected and then I can make a new release.

**Comment by blu3beri** [comment]
It works as intended! thanks!
